name: workflow
on:
    workflow_dispatch:
    pull_request:
        branches: [develop]
    push:
        branches: [develop]
    schedule:
        - cron: "0 0 * * *"

jobs:
    job_1:
        name: Build on Ubuntu
        runs-on: ubuntu-latest
        steps:
            # Pobranie repozytorium
            - name: Checkout
              uses: actions/checkout@v4

            # Instalacja toolchaina ARM
            - name: Install ARM GCC
              uses: ryanwinter/arm-none-eabi-gcc@master
              with:
                release: '10.3-2021.10'

            # Sprawdzenie wersji kompilatora (aby upewnić się, że jest w PATH)
            - name: Check ARM GCC version
              run: arm-none-eabi-gcc --version

            # Czyszczenie starej kompilacji
            - name: Clean
              run: make clean

            # Budowanie całego projektu
            - name: Build
              run: make all

    job_2:
        name: Build on Windows
        runs-on: windows-latest
        needs: job_1
        steps:
            # Pobranie repozytorium
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download and Install ARM GCC 12.3 on Windows
              run: |
                Invoke-WebRequest -Uri "https://developer.arm.com/-/media/Files/downloads/gnu/12.3.rel1/gcc-arm-12.3.rel1-win32.exe" -OutFile "gcc-arm.exe"
                Start-Process -FilePath "gcc-arm.exe" -ArgumentList "/S" -NoNewWindow -Wait
                echo "C:\Program Files (x86)\GNU Arm Embedded Toolchain\12.3.rel1\bin" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH

            - name: Check ARM GCC version
              run: arm-none-eabi-gcc --version

            # Czyszczenie starej kompilacji
            - name: Clean
              run: make clean

            # Budowanie całego projektu
            - name: Build
              run: make all
            
            # Zapisywanie wyników kompilacji jako artefakt
            - name: Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: Build
                path: |
                  build/*.hex
                  build/*.elf
                  build/*.bin
                  build/*.map
