name: workflow
on:
    workflow_dispatch:
    pull_request:
        branches: [develop]
    push:
        branches: [develop]
    schedule:
        - cron: "0 0 * * *"

jobs:
    job_1:
        name: Build on Ubuntu
        runs-on: ubuntu-latest
        steps:
            # Pobranie repozytorium
            - name: Checkout
              uses: actions/checkout@v4

            # Instalacja toolchaina ARM
            - name: Install ARM GCC
              uses: ryanwinter/arm-none-eabi-gcc@master
              with:
                release: '10.3-2021.10'

            # Sprawdzenie wersji kompilatora (aby upewnić się, że jest w PATH)
            - name: Check ARM GCC version
              run: arm-none-eabi-gcc --version

            # Czyszczenie starej kompilacji
            - name: Clean
              run: make clean

            # Budowanie całego projektu
            - name: Build
              run: make all

    job_2:
        name: Build on Windows
        runs-on: windows-latest
        needs: job_1
        steps:
            # Pobranie repozytorium
            - name: Checkout
              uses: actions/checkout@v4

            - name: Get latest ARM GCC 12.3 release
              id: get_gcc_url
              run: |
                $release = Invoke-RestMethod -Uri "https://api.github.com/repos/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/latest"
                $asset = $release.assets | Where-Object { $_.name -match "win32-x64.zip$" }
                if ($asset -eq $null) { Write-Error "No matching asset found!" }
                echo "gcc_url=$($asset.browser_download_url)" >> $env:GITHUB_ENV
              shell: pwsh

            - name: Download and Install ARM GCC 12.3 on Windows
              run: |
                Invoke-WebRequest -Uri "${{ env.gcc_url }}" -OutFile "gcc-arm.zip"
                Expand-Archive -Path "gcc-arm.zip" -DestinationPath "$env:GITHUB_WORKSPACE\gcc-arm"
                echo "$env:GITHUB_WORKSPACE\gcc-arm\xpack-arm-none-eabi-gcc-12.3.1-1\bin" | Out-File -Append -Encoding utf8 $env:GITHUB_PATH
              shell: pwsh

            - name: Check ARM GCC version
              run: |
                $env:Path += ";$env:GITHUB_WORKSPACE\gcc-arm\xpack-arm-none-eabi-gcc-12.3.1-1\bin"
                arm-none-eabi-gcc --version
              shell: pwsh

            - name: Check ARM GCC version
              run: arm-none-eabi-gcc --version

            # Czyszczenie starej kompilacji
            - name: Clean
              run: make clean

            # Budowanie całego projektu
            - name: Build
              run: make all
            
            # Zapisywanie wyników kompilacji jako artefakt
            - name: Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: Build
                path: |
                  build/*.hex
                  build/*.elf
                  build/*.bin
                  build/*.map
