name: workflow1

on:
    workflow_dispatch:
    pull_request:
        branches: [develop]
jobs:
    job_1:
        name: Job_1
        runs-on: ubuntu-latest
        steps:
            - name: Step1
              run: echo "Run Job1 step1"
    job_2:
        name: Job_2
        runs-on: windows-latest
        needs: job_1
        steps:
            - name: Step1
              run: echo "Run Job2 step1"